# The URL the site will be built for
base_url = "https://test-gos-blog.github.io"
title = "GrapheneOS Test Blog"
description = "A test GOS blog."

# Default author for posts (for atom feeds)
author = "GrapheneOS Team"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# TODO, maybe
# Whether to build a search index to be used later on by a JavaScript library
# build_search_index = true

#[search]
#index_format = "elasticlunr_json"
#include_description = true
#include_content = true

[markdown]
external_links_target_blank = true
external_links_no_referrer = true

[extra]
canonical_base_url = "https://grapheneos.org"
