# The URL the site will be built for
base_url = "https://test-gos-blog.github.io"
title = "GrapheneOS Test Blog"
description = "A test GrapheneOS blog."

# Default author, but can be overridden for individual posts.
author = "GrapheneOS Team"

exclude_paginated_pages_in_sitemap = "all"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# TODO, maybe
# Whether to build a search index to be used later on by a JavaScript library
# build_search_index = true

#[search]
#index_format = "elasticlunr_json"
#include_description = true
#include_content = true

[markdown]
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
external_links_external = true

[extra]
canonical_base_url = "https://test-gos-blog.github.io"
github_repo = "https://github.com/test-gos-blog/test-gos-blog.github.io"
